<?php

use CRM_Uimods_ExtensionUtil as E;

return [
  'at_greenpeace_uimods_config' => [
    'group_name' => 'GP UIMods',
    'group' => 'at_greenpeace_uimods',
    'name' => 'at_greenpeace_uimods_config',
    'type' => 'Array',
    'default' => [],
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Stored information on custom fields',
  ],
  'at_greenpeace_uimods_preferred_language' => [
    'group_name' => 'GP UIMods',
    'group' => 'at_greenpeace_uimods',
    'name' => 'at_greenpeace_uimods_preferred_language',
    'type' => 'string',
    'default' => 'de_DE',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Default preferred language for new contacts',
  ],
  'at_greenpeace_uimods_token_sql_task_id' => [
    'group_name' => 'GP UIMods',
    'group' => 'at_greenpeace_uimods',
    'name' => 'at_greenpeace_uimods_token_sql_task_id',
    'type' => 'integer',
    'default' => NULL,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'SQL Task called to generate contact tokens',
  ],
  'at_greenpeace_uimods_sms_default_location_type_id' => [
    'group_name' => 'GP UIMods',
    'group' => 'at_greenpeace_uimods',
    'name' => 'at_greenpeace_uimods_sms_default_location_type_id',
    'type' => 'integer',
    'default' => NULL,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Default location type for new phone numbers generated from inbound SMS',
  ],
  'at_greenpeace_uimods_sms_discard_unknown_sender' => [
    'group_name' => 'GP UIMods',
    'group' => 'at_greenpeace_uimods',
    'name' => 'at_greenpeace_uimods_sms_discard_unknown_sender',
    'type' => 'Boolean',
    'default' => FALSE,
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Discard SMS from unknown sender?',
  ],
  'at_greenpeace_uimods_activity_assignees_filter_group_name' => [
    'group_name' => 'GP UIMods',
    'group' => 'at_greenpeace_uimods',
    'name' => 'at_greenpeace_uimods_activity_assignees_filter_group_name',
    'type' => 'string',
    'default' => '',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Group name, which uses for filter at "activity_assignees" field.',
  ],
  'allowed_email_workflows' => [
    'name'        => 'allowed_email_workflows',
    'type'        => 'Array',
    'html_type'   => 'text',
    'default'     => [
      '/^password_reset$/',
      '/^test_preview$/',
    ],
    'add'         => '1.0',
    'title'       => E::ts('Allowed Email Workflows'),
    'description' => E::ts(
      'Allowlist of email workflows (message templates) in RegEx format which are allowed to be used for outbound emails.'
           . 'Attempting to send workflows not listed here will raise an Exception to prevent accidental email communication to supporters.'),
    'is_domain'   => 1,
    'is_contact'  => 0,
  ],
  'iap_session_refresh_enabled' => [
    'name'       => 'iap_session_refresh_enabled',
    'type'       => 'Boolean',
    'default'    => FALSE,
    'add'        => '1.10',
    'title'      => ts('Refresh IAP session periodically?'),
    'is_domain'  => 1,
    'is_contact' => 0,
    'description' => 'Should the Identity-Aware Proxy session be refreshed periodically?',
  ],
 ];
