-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_uimods_token`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_uimods_token
-- *
-- *******************************************************/
CREATE TABLE `civicrm_uimods_token` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique UimodsToken ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `tokens` longtext COMMENT 'Tokens (JSON)',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_contact_id`(contact_id),
  CONSTRAINT FK_civicrm_uimods_token_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
