-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_uimods_token`;
DROP TABLE IF EXISTS `civicrm_uimods_template`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_uimods_template
-- *
-- *******************************************************/
CREATE TABLE `civicrm_uimods_template` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ApiLog ID',
  `scope_name` varchar(60) NOT NULL COMMENT 'Scope name of template',
  `target_value` varchar(100) NOT NULL COMMENT 'Target value',
  `field_name` varchar(100) NOT NULL COMMENT 'Field name',
  `field_value` longtext DEFAULT NULL COMMENT 'Field value',
  `field_type` varchar(30) NOT NULL COMMENT 'Field type',
  `is_field_hidden` tinyint NOT NULL COMMENT 'Is field hidden?',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `updated_at` datetime NOT NULL DEFAULT NOW() COMMENT 'Updated at date',
  `created_at` datetime NOT NULL DEFAULT NOW() COMMENT 'Created at date',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_uimods_template_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_uimods_token
-- *
-- *******************************************************/
CREATE TABLE `civicrm_uimods_token` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique UimodsToken ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `tokens` longtext COMMENT 'Tokens (JSON)',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_contact_id`(contact_id),
  CONSTRAINT FK_civicrm_uimods_token_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
